# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c78278eba57e38ab8423cda2ea0cbbc3bd327b553e829b4fa62d804a0039eb684307c083476ceea250b0b816ca921798ffa33bb0bcf457d477f13b86c9b877c

test:
  secret_key_base: 4e4b32cd4808a392ac08282768fbe40cad1cd000c334538c9e47dd2d726c2fd3644102846264819d3ca1365993954a8e4f9213455c58cfc978849dc0d2916f22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
